training:
  model_name: "jsfakes_garland_minillama"
  batch_size: 48
  lr: 0.001
  lr_warmup_steps: "10%"
  lr_decay_until_steps: "auto"
  lr_decay_factor: 0.001
  weight_decay: 0.1
  amp_precision: bfloat16
  weight_precision: float32
  enable_mixed_precision: true
  num_epochs: 10
  output_dir: "output/jsfakes_garland_minillama"
  save_every_step: 500
  log_every_step: 10
  wandb_project: "jsfakes_garland"
  torch_compile: false

model:
  type: "minillama"
  hidden_size: 64
  n_layer: 4
  n_head: 4
  n_local_heads: 4
  n_local_kv_heads: 4
  num_key_value_heads: 4
  attention_dropout: 0.0
  fc_scale: 2
  context_length: 2048
  rope_theta: 64
  eps: 1e-6
  rms_norm_eps: 1e-6


dataset:
  hugging_face_id: "TristanBehrens/jsfakes_garland_2024-100K"
  
tokenizer:
  type: "whitespace"
  fill_token: "[EOS]"

