training:
  model_name: "jsfakes_garland_minlstm"
  batch_size: 48
  lr: 0.001
  lr_warmup_steps: "10%"
  lr_decay_until_steps: "auto"
  lr_decay_factor: 0.001
  weight_decay: 0.1
  amp_precision: bfloat16
  weight_precision: float32
  enable_mixed_precision: true
  num_epochs: 10
  output_dir: "output/jsfakes_garland_minlstm"
  save_every_step: 500
  log_every_step: 10
  wandb_project: "jsfakes_garland"
  torch_compile: false

model:
  type: "minlstm"
  hidden_size: 128
  num_hidden_layers: 8
  ff_mult: 4
  context_length: 2048

dataset:
  hugging_face_id: "TristanBehrens/jsfakes_garland_2024-100K"
  
tokenizer:
  type: "whitespace"
  fill_token: "[EOS]"

