training:
  model_name: "musicxlstm_dsr"
  batch_size: 8
  lr: 0.001
  lr_warmup_steps: 2000
  lr_decay_until_steps: 20000
  lr_decay_factor: 0.001
  weight_decay: 0.1
  amp_precision: bfloat16
  weight_precision: float32
  enable_mixed_precision: true
  mixed_precision: bf16
  num_epochs: 15
  output_dir: "output/musicxlstm_local"
  save_every_step: 100
  log_every_step: 10
  wandb_project: "music_dsr"
  torch_compile: false


model:
  num_blocks: 2
  embedding_dim: 64
  mlstm_block:
    mlstm:
      num_heads: 1
  slstm_block:
    slstm:
      num_heads: 1
  slstm_at: [1]
  context_length: 4096




dataset:
  hugging_face_id: "k-hassan/music_dsr"
  
tokenizer:
  type: "whitespace"
  fill_token: "[EOS]"