training:
  model_name: "metal-tonnetz-r8-split-allinstruments"
  batch_size: 32
  lr: 0.001
  lr_warmup_steps: "10%"
  lr_decay_until_steps: "auto"
  lr_decay_factor: 0.001
  weight_decay: 0.1
  amp_precision: bfloat16
  weight_precision: float32
  enable_mixed_precision: true
  num_epochs: 5
  output_dir: "output/metal-tonnetz-r8-split-allinstruments"
  save_every_step: 500
  log_every_step: 10
  wandb_project: "tonnetz"
  torch_compile: false

model:
  type: "llamathree"
  context_length: 2048
  emb_dim: 64
  n_heads: 4
  n_layers: 4
  hidden_dim: 128
  hidden_activation: "silu"
  n_kv_groups: 1
  rope_base: 50_000
  rope_freq: null
  dtype: float32

dataset:
  hugging_face_id: "TristanBehrens/metal-tonnetz-r8-split-allinstruments"
  
tokenizer:
  type: "whitespace"
  fill_token: "[EOS]"

