description: "Train a Lovecraft LSTM model on the Lovecraft corpus."

training:
  model_name: "openwebtext-xlstm"
  batch_size: 64
  lr: 0.001
  lr_warmup_steps: 20
  lr_decay_until_steps: "auto"
  lr_decay_factor: 0.001
  weight_decay: 0.1
  amp_precision: bfloat16
  weight_precision: float32
  enable_mixed_precision: true
  num_epochs: 10
  output_dir: "output/openwebtext-xlstm"
  save_every_step: 100
  log_every_step: 10
  wandb_project: "openwebtext-xlstm"

model:
  num_blocks: 2
  embedding_dim: 64
  mlstm_block:
    mlstm:
      num_heads: 1
  slstm_block:
    slstm:
      num_heads: 1
  slstm_at: [1]
  context_length: 256

dataset:
  hugging_face_id: "Skylion007/openwebtext"
  
tokenizer:
  type: "pretrained"
  pretrained_class: "GPT2Tokenizer"
  pretrained_id: "openai-community/gpt2"

