description: "Train xLSTM on the OpenWebText corpus. https://huggingface.co/datasets/Skylion007/openwebtext"

training:
  model_name: "openwebtext-xlstm"
  batch_size: 4
  gradient_accumulation_steps: 4
  lr: 0.001
  lr_warmup_steps: 20
  lr_decay_until_steps: "auto"
  lr_decay_factor: 0.001
  weight_decay: 0.1
  amp_precision: bfloat16
  weight_precision: float32
  enable_mixed_precision: true
  num_epochs: 1
  output_dir: "output/openwebtext-xlstm"
  save_every_step: 10000
  log_every_step: 100
  wandb_project: "openwebtext-xlstm"

dataset:
  hugging_face_id: "Skylion007/openwebtext"
  
tokenizer:
  type: "pretrained"
  pretrained_class: "GPT2Tokenizer"
  pretrained_id: "openai-community/gpt2"

